name: finance_digest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  fluttertoast: ^8.2.8
  go_router: ^14.4.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.15.0

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Regular
       fonts:
         - asset: fonts/Roboto-Regular.ttf

     - family: Medium
       fonts:
         - asset: fonts/Roboto-Medium.ttf

     - family: Bold
       fonts:
         - asset: fonts/Roboto-Bold.ttf

